spring.web.resources.static-locations: classpath:/static/
spring:
  mvc:
    static-path-pattern: /static/**
management:
  endpoint:
    configprops:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env,health,configprops,info
  server:
    port: 8081
