name: Docker

on:
  push:
    branches: [ main ]
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Determine tag for Docker image
        id: determine-tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=snapshot" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@5f4866a30a54f16a52d2ecb4a3898e9e424939cf
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t heapdive .

      - name: Tag Docker image
        run: docker tag heapdive tokuhirom/heapdive:${{ steps.determine-tag.outputs.tag }}

      - name: Build and push Docker image
        run: docker push tokuhirom/heapdive:${{ steps.determine-tag.outputs.tag }}
