name: Build and Release JAR

on:
  release:
    types:
      - created

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew -PreleaseVersion=${{github.event.release.tag_name}} :heapdive-cli:build

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./heapdive-cli/build/libs/heapdive-cli-${{ github.event.release.tag_name }}-all.jar
          asset_name: heapdive-cli-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive
